modLoader="javafml"
loaderVersion="[63,)"
license="All Rights Reserved"
#issueTrackerURL="https://github.com/MyOrganization/MyMod/" #optional
#clientSideOnly=true #optional, default=false

[[mods]]
modId="bluthchix"
version="1.1.1"
displayName="Bluth Family Poultry"
#updateJSONURL="https://example.com/updates.json" #optional
#displayURL="https://example.com/" #optional
#logoFile="bluthchix.png" #optional
#credits="" #optional
authors="Dan Wilson" #optional
#displayTest="MATCH_VERSION" #optional, default=MATCH_VERSION when not clientSideOnly, else IGNORE_ALL_VERSION

description='''Replaces chicken ambient sounds with custom ones.'''

[[dependencies.bluthchix]] #recommended
    modId="forge"
    mandatory=true
    versionRange="[63,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bluthchix]] #recommended
    modId="minecraft"
    mandatory=true
    versionRange="[26.1.1,27)"
    ordering="NONE"
    side="BOTH"
